export const initialValues = {
    campaignName: "",
    month: "",
    isLead: false,
    category: "",
    targetingMethod: "",
    creativeType: "",
    location: "",
    segment: "",
};

export const optionsValues = {
    months: [
        { value: "Jan", key: "Jan" },
        { value: "Feb", key: "Feb" },
        { value: "Mar", key: "Mar" },
        { value: "Apr", key: "Apr" },
        { value: "May", key: "May" },
        { value: "Jun", key: "Jun" },
        { value: "Jul", key: "Jul" },
        { value: "Aug", key: "Aug" },
        { value: "Sep", key: "Sep" },
        { value: "Oct", key: "Oct" },
        { value: "Nov", key: "Nov" },
        { value: "Dec", key: "Dec" },
    ],
    adCategory: [
        { value: "Stories", key: "STORIES" },
        { value: "Weather", key: "WEATHER" },
        { value: "In Stream", key: "IN_STREAM" },
        { value: "Bumper", key: "BUMPER" },
        { value: "Discovery", key: "DISCOVERY" },
        { value: "Flight", key: "FLIGHT" },
        { value: "OTA", key: "OTA" },
        { value: "Sequence", key: "SEQUENCE" },
    ],
    targetingMethod: [
        { value: "Audience", key: "AUDIENCE" },
        { value: "List", key: "LIST" },
        { value: "Lookalike", key: "LOOKALIKE" },
        { value: "Retargeting", key: "RETARGETING" },
        { value: "Dynamic Retargeting", key: "DYNAMIC_RETARGETING" },
        { value: "Placement", key: "PLACEMENT" },
        { value: "Keyword", key: "KEYWORD" },
    ],
    creativeType: [
        { value: "Static", key: "STATIC" },
        { value: "Carousel", key: "CAROUSEL" },
        { value: "Video", key: "VIDEO" },
        { value: "Cinemagraph", key: "CINEMAGRAPH" },
        { value: "Text", key: "TEXT" },
        { value: "Dynamic Static", key: "DYNAMIC_STATIC" },
        { value: "Dynamic Video", key: "DYNAMIC_VIDEO" },
        { value: "HTML", key: "HTML" },
        { value: "GIF", key: "GIF" },
        { value: "Audio", key: "AUDIO" },
    ],
};
